theme: jekyll-theme-cayman
title: 'Weakly Supervised Computer Vision'
description:
- "at the <a href='https://deeplearningindaba.com/2022/' target='_blank' style='text-decoration: underline; text-shadow: none;'>Deep Learning Indaba</a>"
- August 25, 2022
- Tunis, Tunisia and Online
repository: xxx/my-github-projects
buttons:
  Overview: './#overview'
  Invited Speakers: './#invited-speakers'
  Program: './#program'
  Organizers: './#organizers'
  Call for Papers: './#call-for-papers'
  Important Dates: './#important-workshop-dates'
github:
  is_project_page: false
