theme: jekyll-theme-cayman
title: 'Weakly Supervised Computer Vision'
repository: xxx/my-github-projects
editions:
  - 2023
  - 2022
github:
  is_project_page: false

# Google Analytics
google_analytics: G-0CG00X9EN0

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
